spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: root
    password: root
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.flywaydb.core: DEBUG
